name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.406'  # Change to your .NET version

      - name: Publish .NET App
        run: dotnet publish -c Release -o publish

      - name: Copy Files to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 2.tcp.eu.ngrok.io
          port: 10266 
          username: tjotola
          key: ${{ secrets.PI_SSH_KEY }}
          source: "publish/*"
          target: "/home/pi/app"
          debug: true  # Enable debug logging

      - name: Start Application on Raspberry Pi
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 2.tcp.eu.ngrok.io
          port: 10266 
          username: tjotola
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            # Start application using 'dotnet run' directly
            echo "Starting application..."
            dotnet /home/pi/app/publish/Gaming.Api.dll
