name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.406'  # Change to your .NET version

      - name: Publish .NET App
        run: dotnet publish -c Release -o publish

      - name: Copy Files to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 7.tcp.eu.ngrok.io
          port: 18816
          username: tjotola
          key: ${{ secrets.PI_SSH_KEY }}
          source: "publish/*"
          target: "/home/pi/app"
          debug: true  # Enable debug logging

      - name: Restart Application on Raspberry Pi
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 7.tcp.eu.ngrok.io
          port: 18816
          username: tjotola
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            sudo mkdir -p /home/pi/app 
            pkill -f "dotnet /home/pi/app/GamingAPI.dll" || true
            nohup dotnet /home/pi/app/GamingAPI.dll > /home/pi/app/logs.txt 2>&1 &



