name: Deploy to On-Prem Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Build and Publish
      run: |
        dotnet restore
        dotnet publish -c Release -o ./publish

    - name: Deploy to Linux Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          sudo systemctl stop VideoGameApi
          sudo rm -rf /var/www/VideoGameApi
          mkdir -p /var/www/VideoGameApi
          rsync -avz ./publish/ /var/www/VideoGameApi/
          sudo systemctl restart VideoGameApi
