name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.486'

    - name: Publish .NET app
      run: |
        dotnet publish -c Release -o publish

    - name: Install sshpass (if not installed)
      run: sudo apt-get install -y sshpass

    - name: Deploy to Raspberry Pi with password
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -r publish/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_DIR }}
    
    - name: Restart API on Raspberry Pi with password
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ${{ secrets.DEPLOY_DIR }} && nohup dotnet Gaming.Api.dll > output.log 2>&1 &'
